name = "Particle-Swarm-Optimization-Fortran-95"
version = "0.1.0"
license = "license"
author = "Mohammad Asif Zaman"
maintainer = "http://web.stanford.edu/~zaman/"
copyright = "Copyright 2024,  Mohammad Asif Zaman "
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

